# Generated by Django 3.0.1 on 2019-12-29 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_uploadimage_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='uploadImage',
            field=models.ImageField(blank=True, null=True, upload_to='uploadImage'),
        ),
    ]
