# Generated by Django 3.0.1 on 2019-12-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20191229_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='rotateImage',
            field=models.ImageField(blank=True, null=True, upload_to='rotateImage'),
        ),
    ]
