# Generated by Django 3.0.1 on 2019-12-30 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_uploadimage_rotateimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimage',
            name='rotateImage',
        ),
        migrations.RemoveField(
            model_name='uploadimage',
            name='uploadImage',
        ),
        migrations.RemoveField(
            model_name='uploadimage',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
