# Generated by Django 3.0.1 on 2019-12-30 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20191229_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimage',
            name='image',
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='uploadImage',
            field=models.ImageField(blank=True, null=True, upload_to='uploadImage'),
        ),
    ]
