# Generated by Django 3.0.1 on 2020-01-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20191229_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimage',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
