# Generated by Django 3.0.1 on 2020-01-02 03:01

from django.db import migrations
import exiffield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_uploadimage_exif'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='exif',
            field=exiffield.fields.ExifField(default={}, editable=False),
        ),
    ]
