# Generated by Django 3.0.1 on 2020-01-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_uploadimage_exif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimage',
            name='exif',
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='pre_save',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
